spring:
    datasource:
        username: moqiqi
        password: moqiqi
        url: jdbc:mysql://192.168.3.157:3306/test?characterEncoding=UTF-8&useSSL=false
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
    sql:
        init:
            mode: never
    application:
        name: stock-seata
    cloud:
        nacos:
            discovery:
                server-addr: 192.168.3.157:8848
mybatis:
    configuration:
        map-underscore-to-camel-case: true
server:
    port: 7071
seata:
    tx-service-group: default_tx_group
    registry:
        type: nacos
        nacos:
            application: seata-server
            server-addr: 192.168.3.157:8848
            group: SEATA_GROUP
    config:
        type: nacos
        nacos:
            server-addr: 192.168.3.157:8848
