server:
    port: 7771
spring:
    application:
        name: order-service
    cloud:
        nacos:
            discovery:
                server-addr: 192.168.3.157:8848
                namespace: public
        openfeign:
            client:
                config:
                  stock-service:
                      logger-level: FULL
                      connect-timeout: 5000
                      read-timeout: 3000
                      request-interceptors[0]: moe.mqq.interceptor.CustomFeignInterceptor
logging:
    level:
      moe.mqq.feign: debug